### ISSUE TITLE
Nextjs with Strapi CMS

### ISSUE THREAD

**Issue by marksantiago290** [BTC415/Next-reviews#10]
I used Headless CMS for storing reviews data in Nextjs, The Headless CMS opens on port 1337 and Nextjs uses port 3000, I deployed this project to vercel, but I cannot call the reviews data. How to fix this?

**Comment by imcrazysteven** [comment]
Hi. If you are using Strapi as your Headless CMS and having trouble accessing the reviews data in your Next.js application after deploying to Vercel, here are specific steps to follow:

1. Deploy Strapi
Ensure you have Strapi properly deployed and accessible over the internet. If you are using a service like Heroku, DigitalOcean, or any other cloud provider, make sure your Strapi instance is running and publicly accessible.

2. Update Environment Variables
In your Next.js application, you need to set environment variables to access your Strapi API URL:

Go to your Vercel project settings.
Under "Environment Variables," add a variable, e.g., NEXT_PUBLIC_CMS_URL, with the value being your Strapi instance's URL (e.g., https://your-strapi-url.com).
3. Use the Environment Variable in Your Next.js Application
Update your API calls in Next.js to use this environment variable:

4. CORS Settings in Strapi
Make sure Strapi is configured to allow requests from your Vercel domain:
Open the config/middlewares.js file in your Strapi project.
Look for the CORS settings and ensure it is allowing your Vercel domain.

5. Check Strapi Permissions
Make sure that the necessary permissions for accessing the reviews API are set correctly in the Strapi Admin panel:

Hoping this will be a solution to this issue.
Good luck
